
export enum Direction {
    STRAIGHT_UP,
    STRAIGHT_UP_RIGHT,
    STRAIGHT_RIGHT,
    STRAIGHT_RIGHT_DOWN,
    STRAIGHT_DOWN,
    STRAIGHT_DOWN_LEFT,
    STRAIGHT_LEFT,
    STRAIGHT_LEFT_UP,
    ONE_UP,
    ONE_RIGHT,
    ONE_DOWN,
    ONE_LEFT
}
